### ISSUE TITLE
[BUG] Value after * must be an iterable, not NoneType

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#132]
```
2023-01-05T15:10:30.503250+00:00 app[worker.1]: 2023-01-05 15:10:30,502 - ERROR - pyrogram.client - MainThread - Value after * must be an iterable, not NoneType
2023-01-05T15:10:30.503262+00:00 app[worker.1]: Traceback (most recent call last):
2023-01-05T15:10:30.503263+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/client.py", line 922, in get_file
2023-01-05T15:10:30.503264+00:00 app[worker.1]:     r = await session.invoke(
2023-01-05T15:10:30.503264+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
2023-01-05T15:10:30.503265+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2023-01-05T15:10:30.503266+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 337, in send
2023-01-05T15:10:30.503266+00:00 app[worker.1]:     await self.connection.send(payload)
2023-01-05T15:10:30.503266+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 69, in send
2023-01-05T15:10:30.503266+00:00 app[worker.1]:     await self.protocol.send(data)
2023-01-05T15:10:30.503267+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp_abridged_o.py", line 61, in send
2023-01-05T15:10:30.503267+00:00 app[worker.1]:     payload = await self.loop.run_in_executor(pyrogram.crypto_executor, aes.ctr256_encrypt, data, *self.encrypt)
2023-01-05T15:10:30.503267+00:00 app[worker.1]: TypeError: Value after * must be an iterable, not NoneType
```

**Comment by EDM115** [comment]
Probably an internal issue from Pyrogram
not impacting anything
