### ISSUE TITLE
/me error

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#15]
```
2022-04-26T22:21:17.685149+00:00 app[worker.1]: name 'unzip_bot' is not defined
2022-04-26T22:21:17.685166+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-26T22:21:17.685167+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-04-26T22:21:17.685168+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-04-26T22:21:17.685169+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
2022-04-26T22:21:17.685170+00:00 app[worker.1]:     await self.user_callback(client, message, *args)
2022-04-26T22:21:17.685171+00:00 app[worker.1]:   File "/app/unzipper/modules/commands.py", line 164, in me_stats
2022-04-26T22:21:17.685171+00:00 app[worker.1]:     me_info = await unzip_bot.ask(chat_id=query.message.chat.id ,text="Send anything :")
2022-04-26T22:21:17.685172+00:00 app[worker.1]: NameError: name 'unzip_bot' is not defined
```

**Comment by EDM115** [comment]
Definitely fixed [here](https://github.com/EDM115/unzip-bot/commit/fc8d9dc6738dabfc255b4a7548af2334db9c9bd2)
