### ISSUE TITLE
One file not extracted causes InlineKeyboard bug

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#16]
```
2022-04-24T14:10:59.103370+00:00 app[worker.1]: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
2022-04-24T14:10:59.103380+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-24T14:10:59.103381+00:00 app[worker.1]:   File "/app/unzipper/modules/ext_script/up_helper.py", line 40, in send_file
2022-04-24T14:10:59.103382+00:00 app[worker.1]:     os.remove(doc_f)
2022-04-24T14:10:59.103383+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: '/app/NexaBots/1477175157/extracted/5L'
2022-04-24T14:10:59.103383+00:00 app[worker.1]: 
2022-04-24T14:10:59.103384+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-04-24T14:10:59.103384+00:00 app[worker.1]: 
2022-04-24T14:10:59.103384+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-24T14:10:59.103385+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-04-24T14:10:59.103385+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-04-24T14:10:59.103385+00:00 app[worker.1]:   File "/app/unzipper/modules/callbacks.py", line 187, in unzipper_cb
2022-04-24T14:10:59.103385+00:00 app[worker.1]:     await send_file(unzip_bot=unzip_bot,
2022-04-24T14:10:59.103386+00:00 app[worker.1]:   File "/app/unzipper/modules/ext_script/up_helper.py", line 45, in send_file
2022-04-24T14:10:59.103386+00:00 app[worker.1]:     await query.answer("Sorry! I can't find that file", show_alert=True)
2022-04-24T14:10:59.103386+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 163, in answer
2022-04-24T14:10:59.103387+00:00 app[worker.1]:     return await self._client.answer_callback_query(
2022-04-24T14:10:59.103387+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 71, in answer_callback_query
2022-04-24T14:10:59.103387+00:00 app[worker.1]:     return await self.send(
2022-04-24T14:10:59.103388+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2022-04-24T14:10:59.103388+00:00 app[worker.1]:     r = await self.session.send(
2022-04-24T14:10:59.103388+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
2022-04-24T14:10:59.103388+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2022-04-24T14:10:59.103388+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
2022-04-24T14:10:59.103389+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-04-24T14:10:59.103389+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-04-24T14:10:59.103389+00:00 app[worker.1]:     raise getattr(
2022-04-24T14:10:59.103390+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
```

**Comment by EDM115** [comment]
Nothing serious but I may need to fix that

**Comment by EDM115** [comment]
```
2022-04-27T17:01:36.351080+00:00 app[worker.1]: [5] Retrying "messages.SendMedia" due to Telegram says: [500 RPC_CALL_FAIL] - Telegram is having internal problems. Please try again later (caused by "messages.SendMedia")
2022-04-27T17:01:39.133391+00:00 app[worker.1]: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
2022-04-27T17:01:39.133398+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-27T17:01:39.133399+00:00 app[worker.1]:   File "/app/unzipper/modules/ext_script/up_helper.py", line 25, in send_file
2022-04-27T17:01:39.133399+00:00 app[worker.1]:     u_file_size = os.stat(doc_f).st_size
2022-04-27T17:01:39.133401+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: '/app/NexaBots/1590098758/extracted/CHVRCHES - The Bones of What You Believe (Asia Deluxe Edition)  [1442649778]/(1x14) CHVRCHES - Broken Bones.m4a'
2022-04-27T17:01:39.133401+00:00 app[worker.1]: 
2022-04-27T17:01:39.133402+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-04-27T17:01:39.133402+00:00 app[worker.1]: 
2022-04-27T17:01:39.133402+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-27T17:01:39.133403+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-04-27T17:01:39.133403+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-04-27T17:01:39.133404+00:00 app[worker.1]:   File "/app/unzipper/modules/callbacks.py", line 187, in unzipper_cb
2022-04-27T17:01:39.133404+00:00 app[worker.1]:     await send_file(unzip_bot=unzip_bot,
2022-04-27T17:01:39.133404+00:00 app[worker.1]:   File "/app/unzipper/modules/ext_script/up_helper.py", line 45, in send_file
2022-04-27T17:01:39.133405+00:00 app[worker.1]:     await query.answer("Sorry! I can't find that file", show_alert=True)
2022-04-27T17:01:39.133405+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 163, in answer
2022-04-27T17:01:39.133406+00:00 app[worker.1]:     return await self._client.answer_callback_query(
2022-04-27T17:01:39.133406+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 71, in answer_callback_query
2022-04-27T17:01:39.133406+00:00 app[worker.1]:     return await self.send(
2022-04-27T17:01:39.133407+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2022-04-27T17:01:39.133407+00:00 app[worker.1]:     r = await self.session.send(
2022-04-27T17:01:39.133407+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
2022-04-27T17:01:39.133408+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2022-04-27T17:01:39.133408+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
2022-04-27T17:01:39.133408+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-04-27T17:01:39.133409+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-04-27T17:01:39.133409+00:00 app[worker.1]:     raise getattr(
2022-04-27T17:01:39.133410+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
```

**Comment by EDM115** [comment]
#1
