### ISSUE TITLE
Reply markup too long

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#2]
```
ERROR: Telegram says: [400 REPLY_MARKUP_TOO_LONG] - The reply markup is too long (caused by "messages.SendMessage")
```

**Comment by EDM115** [comment]
This happen when they are more items than the max of 100 inline buttons limit  
Can be solved by reducing the max authorized before all items disappear for an `Upload all` only  
But it works already with archives that contains +1k elements so… it might be a problem with some specific archives  
Faced the same with APK ones

**Comment by EDM115** [comment]
```
2022-05-19 22:06:40,992 - ERROR - pyrogram.dispatcher - MainThread - name 'LOGGER' is not defined
Traceback (most recent call last):
  File "/app/unzipper/modules/callbacks.py", line 160, in unzipper_cb
    await query.message.edit("Select files to upload 👇", reply_markup=i_e_buttons)
  File "/usr/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2742, in edit_text
    return await self._client.edit_message_text(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/edit_message_text.py", line 83, in edit_message_text
    r = await self.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupTooLong: Telegram says: [400 REPLY_MARKUP_TOO_LONG] - The reply markup is too long (caused by "messages.EditMessage")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/unzipper/modules/callbacks.py", line 164, in unzipper_cb
    await unzip_bot.send_message(chat_id=query.message.chat.id, text="Select files to upload 👇", reply_markup=i_e_buttons)
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/send_message.py", line 128, in send_message
    r = await self.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupTooLong: Telegram says: [400 REPLY_MARKUP_TOO_LONG] - The reply markup is too long (caused by "messages.SendMessage")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/unzipper/modules/callbacks.py", line 166, in unzipper_cb
    empty_buttons = await make_keyboard_empty(user_id=user_id, chat_id=query.message.chat.id)
NameError: name 'make_keyboard_empty' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/unzipper/modules/callbacks.py", line 185, in unzipper_cb
    await query.message.edit(Messages.ERROR_TXT.format(e))
  File "/usr/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2742, in edit_text
    return await self._client.edit_message_text(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/edit_message_text.py", line 83, in edit_message_text
    r = await self.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.EditMessage")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/unzipper/modules/callbacks.py", line 192, in unzipper_cb
    LOGGER.error(err)
NameError: name 'LOGGER' is not defined
```

**Comment by EDM115** [comment]
Kinda fixed, only few things remains  
Plus LOGGER error

**Comment by EDM115** [comment]
The biggest bug of the bot have finally be fixed 🥳  
Was not really an error from PyroGram but more PyKeyboard  
Happened when :  
+ Too much elements in a single folder
+ Folder names too long
+ File names too long
+ Any other random error
