### ISSUE TITLE
user_id before assignment in update_uploaded

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#25]
```
2022-05-10T22:50:35.520091+00:00 app[worker.1]: 2022-05-10 22:50:35,519 - pyrogram.dispatcher - ERROR - local variable 'user_id' referenced before assignment
2022-05-10T22:50:35.520093+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-10T22:50:35.520094+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-05-10T22:50:35.520094+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-05-10T22:50:35.520095+00:00 app[worker.1]:   File "/app/unzipper/modules/callbacks.py", line 230, in unzipper_cb
2022-05-10T22:50:35.520095+00:00 app[worker.1]:     update_uploaded(user_id, upload_count=sent_files)
2022-05-10T22:50:35.520096+00:00 app[worker.1]: UnboundLocalError: local variable 'user_id' referenced before assignment
```

**Comment by EDM115** [comment]
Done
