### ISSUE TITLE
Permanant thumbnail support

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#27]
- [x] Save the thumbnail on a separate folder
- [x] Be able to use it while uploading doc
- [x] Use it while uploading media (audio, image) as doc
~~Use it while uploading native pic~~ Will never be possible
- [x] Use it while uploading native audio
- [x] Use it while uploading video as doc
- [x] Use it while upload video as streamable
- [x] Make it permanent by adding to [telegra.ph](https://github.com/python273/telegraph) and db
- [x] Re-download the thumbs on bot start

**Comment by EDM115** [comment]
```
2022-06-05T21:39:45.735118+00:00 app[worker.1]: 2022-06-05 21:39:45,734 - ERROR - pyrogram.dispatcher - MainThread - This message doesn't contain any downloadable media
2022-06-05T21:39:45.735129+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-05T21:39:45.735131+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-06-05T21:39:45.735132+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-06-05T21:39:45.735132+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
2022-06-05T21:39:45.735133+00:00 app[worker.1]:     await self.user_callback(client, message, *args)
2022-06-05T21:39:45.735134+00:00 app[worker.1]:   File "/app/unzipper/modules/commands.py", line 231, in thumb_add
2022-06-05T21:39:45.735134+00:00 app[worker.1]:     await add_thumb(_, message)
2022-06-05T21:39:45.735135+00:00 app[worker.1]:   File "/app/unzipper/modules/ext_script/custom_thumbnail.py", line 27, in add_thumb
2022-06-05T21:39:45.735135+00:00 app[worker.1]:     await _.download_media(
2022-06-05T21:39:45.735136+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/download_media.py", line 113, in download_media
2022-06-05T21:39:45.735136+00:00 app[worker.1]:     raise ValueError("This message doesn't contain any downloadable media")
2022-06-05T21:39:45.735137+00:00 app[worker.1]: ValueError: This message doesn't contain any downloadable media
```

**Comment by EDM115** [comment]
It works ! But in a limited way : pictures, videos and audio with covers still have their automatically generated thumbnail from Telegram…

**Comment by EDM115** [comment]
Good news :  
Performing a local `/clean` or a global `/cleanall` doesn't remove the thumbnails of users 🥰

**Comment by EDM115** [comment]
> Good news : Performing a local `/clean` or a global `/cleanall` doesn't remove the thumbnails of users 🥰

Okay, maybe I were too much optimistic on that 😅

**Comment by EDM115** [comment]
```
2022-08-13 14:30:06,030 - INFO - __main__ - MainThread - Checking Log channel…
2022-08-13 14:30:06,109 - INFO - __main__ - MainThread - Starting bot…
2022-08-13 14:30:06,109 - INFO - __main__ - MainThread - Bot is running now ! Join @EDM115bots
2022-08-13 14:30:51,479 - WARNING - unzipper - MainThread - Downloading thumbnail of 854158484…
2022-08-13 14:30:51,772 - WARNING - unzipper - MainThread - Thumbnail downloaded
2022-08-13 14:30:51,836 - WARNING - unzipper - MainThread - Thumbnail saved
2022-08-13 14:30:58,727 - WARNING - unzipper - MainThread - Error on Telegra.ph upload
2022-08-13 14:30:58,727 - ERROR - pyrogram.dispatcher - MainThread - answer_query() got an unexpected keyword argument 'text'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/unzipper/modules/callbacks.py", line 73, in unzipper_cb
    await answer_query(query, text=Messages.SAVED_THUMBNAIL)
TypeError: answer_query() got an unexpected keyword argument 'text'
2022-08-13 14:32:59,773 - WARNING - unzipper - MainThread - Thumb exists for 854158484
2022-08-13 14:32:59,847 - WARNING - unzipper - MainThread - Downloading thumbnail of 854158484…
2022-08-13 14:32:59,884 - WARNING - unzipper - MainThread - Thumbnail downloaded
2022-08-13 14:32:59,916 - WARNING - unzipper - MainThread - Thumbnail saved
2022-08-13 14:33:07,464 - ERROR - pyrogram.dispatcher - MainThread - 'str' object has no attribute 'to_bytes'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/unzipper/modules/callbacks.py", line 59, in unzipper_cb
    await unzip_bot.delete_messages(chat_id=user_id, message_ids=query.id)
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/delete_messages.py", line 76, in delete_messages
    r = await self.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 291, in _send
    message = self.msg_factory(data)
  File "/usr/lib/python3.10/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/usr/lib/python3.10/site-packages/pyrogram/raw/core/tl_object.py", line 79, in __len__
    return len(self.write())
  File "/usr/lib/python3.10/site-packages/pyrogram/raw/functions/messages/delete_messages.py", line 75, in write
    b.write(Vector(self.id, Int))
  File "/usr/lib/python3.10/site-packages/pyrogram/raw/core/primitives/vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "/usr/lib/python3.10/site-packages/pyrogram/raw/core/primitives/vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "/usr/lib/python3.10/site-packages/pyrogram/raw/core/primitives/int.py", line 33, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
AttributeError: 'str' object has no attribute 'to_bytes'
2022-08-13 14:33:17,961 - WARNING - unzipper - MainThread - Error on Telegra.ph upload
2022-08-13 14:33:17,961 - ERROR - pyrogram.dispatcher - MainThread - answer_query() got an unexpected keyword argument 'text'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/unzipper/modules/callbacks.py", line 73, in unzipper_cb
    await answer_query(query, text=Messages.SAVED_THUMBNAIL)
TypeError: answer_query() got an unexpected keyword argument 'text'
```
