### ISSUE TITLE
Database new user error

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#31]
```
2022-06-05T00:14:10.243076+00:00 app[worker.1]: 2022-06-05 00:14:10,242 - ERROR - pyrogram.dispatcher - MainThread - 'User' object has no attribute 'firstname'
2022-06-05T00:14:10.243085+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-05T00:14:10.243088+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-06-05T00:14:10.243088+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-06-05T00:14:10.243089+00:00 app[worker.1]:   File "/usr/lib/python3.10/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
2022-06-05T00:14:10.243089+00:00 app[worker.1]:     await self.user_callback(client, message, *args)
2022-06-05T00:14:10.243089+00:00 app[worker.1]:   File "/app/unzipper/modules/commands.py", line 43, in _
2022-06-05T00:14:10.243090+00:00 app[worker.1]:     await check_user(message)
2022-06-05T00:14:10.243091+00:00 app[worker.1]:   File "/app/unzipper/helpers/database.py", line 88, in check_user
2022-06-05T00:14:10.243091+00:00 app[worker.1]:     uname = message.from_user.firstname + " " + message.from_user.last_name + " | @" + message.from_user.username
2022-06-05T00:14:10.243092+00:00 app[worker.1]: AttributeError: 'User' object has no attribute 'firstname'
```

**Comment by EDM115** [comment]
[Fixed}(https://github.com/EDM115/unzip-bot/commit/19e7a3582020d32cb643e88a67d1f62f438d82e7) other bug
